name: libmfx

inputs:
  refId:
    type: string
    required: true
  config:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: Build MFX
    shell: cmd
    env:
      vsPath: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\
    run: |
      call "${{ env.vsPath }}VC\Auxiliary\Build\vcvars64.bat"
      md build build\pkgconfig dist
      tar -czvf dist\libmfx.tgz .github\actions\libmfx\include .github\actions\libmfx\lib
      dir /s .github\actions\libmfx
  - name: Publish artifact
    uses: actions/upload-artifact@v2
    with:
      name: libmfx-${{ runner.os }}-${{ inputs.config }}
      path: dist/libmfx.tgz
