name: libmfx

inputs:
  refId:
    type: string
    required: true
  config:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up MSYS2
    uses: msys2/setup-msys2@v2
    with:
      install: base-devel binutils autotools automake mingw-w64-x86_64-cmake nasm
      path-type: inherit
  - name: Build FDK AAC
    shell: cmd
    env:
      vsPath: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\
    run: |
      call "${{ env.vsPath }}VC\Auxiliary\Build\vcvars64.bat"
      md build build/pkgconfig dist
      D:\a\_temp\setup-msys2\msys2.cmd -c 'printf "prefix=$(realpath build)\nexec_prefix=\${prefix}\nincludedir=\${prefix}/include\nlibdir=\${exec_prefix}/lib\nName: libmfx\nDescription: Intel Media SDK Dispatched static library\nVersion: 1.34\nLibs: -L\${libdir} -llibmfx -ladvapi32 -lole32 -luuid\nCflags: -I\${includedir}\n" > .github/actions/libmfx/lib/pkgconfig/libmfx.pc ; tar czf dist/libmfx.tgz .github/actions/libmfx/include .github/actions/libmfx/lib'
      dir /s
  - name: Publish artifact
    uses: actions/upload-artifact@v2
    with:
      name: libmfx-${{ runner.os }}-${{ inputs.config }}
      path: dist/libmfx.tgz
