name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'
        
jobs:

  ffmpeg:
    runs-on: windows-2022
    needs: []
    steps:
      - name: Configure
        shell: cmd
        run: |
          wsl -l -o
          wsl --install -d Debian
          wsl -l -v

