name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'
        
jobs:

  FFmpeg:
    runs-on: windows-2019
    needs: []
    steps:
      - name: Set up development tools
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
         
      - name: Set up development tools2
        shell: cmd
        run: |
          set
          
     # - name: Set up WSL
     #   uses: Vampire/setup-wsl@v1.2.0
     #   with:
     #     additional-packages:
     #       dos2unix
      - name: Build FFmpeg
        shell: wsl-bash {0}
        run: |
          dos2unix vars.sh
          cat vars.sh
          chmod +x vars.sh
          ./vars.sh
          set
          #echo $ABC
          #echo $PATH
          #cl.exe
          #MSBuild.exe
          

          
