name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'
        
env:
  WSLENV: PATH/l
        
jobs:

  FFmpeg:
    runs-on: windows-2019
    needs: []
    steps:
      - name: Set up development tools
        run: |
          set
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build"
          set

          
