name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'

jobs:

  FFmpeg:
    runs-on: windows-2019
    needs: []
    steps:
      - name: Set up development tools
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          FOR /F "delims==" %%G IN ('where cl.exe') DO SET _cl_path=%%G
          echo CL_EXEC="%_cl_path%"
          echo WSL_CL_EXEC=`wslpath -u "$CL_EXEC"`
          echo WSL_CL_PATH=`dirname "$WSL_CL_EXEC"`
          echo export PATH=$PATH:$WSL_CL_PATH
          echo export DevEnvDir="%DevEnvDir% "
          rem ExtensionSdkDir
          rem FSHARPINSTALLDIR
          rem Framework40Version
          rem FrameworkDIR32
          rem FrameworkDir
          rem FrameworkVersion
          rem FrameworkVersion32
          echo export INCLUDE="%INCLUDE% "
          echo export LIB="%LIB% "
          echo export LIBPATH="%LIBPATH% "
          echo export VCINSTALLDIR="%VCINSTALLDIR% "
          echo export VSINSTALLDIR="%VSINSTALLDIR% "
          echo export VisualStudioVersion="%VisualStudioVersion% "
          rem echo export WindowsSDK_ExecutablePath_x64=%WindowsSDK_ExecutablePath_x64%
          rem echo export WindowsSDK_ExecutablePath_x86=%WindowsSDK_ExecutablePath_x86%
          rem echo export WindowsSdkDir=%WindowsSdkDir%
          echo export WSLcross=true
          echo export WSLENV=$WSLENV:INCLUDE/w:LIB/w:LIBPATH/w
      - name: Set up WSL
        uses: Vampire/setup-wsl@v1.2.0
      - name: Build FFmpeg
        shell: wsl-bash {0}
        run: |
          echo $PATH
          cl.exe
          MSBuild.exe
          

          
