name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'

jobs:

  FFmpeg:
    runs-on: windows-2019
    needs: []
    steps:
      - name: Set up WSL
        uses: Vampire/setup-wsl@v1.2.0
        with:
          distribution: Debian
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Set up cache
        uses: actions/cache@v2
        env:
          cache-name: cache-ffmpeg
        with:
          path: ~/build
          key: ${{ env.cache-name }}
#      - name: Get artifacts
#        uses: actions/download-artifact@master
#        with:
#          name: oneVPL
      - name: Build FFmpeg
        shell: wsl-bash {0}
        run: |
          sudo apt-get install git
          git clone -q -b release/5.0 https://github.com/FFmpeg/FFmpeg.git ffmpeg
          mkdir build
          BUILD=$(realpath build)
          tar zxf *.tgz -C build
          cd ffmpeg
          PKG_CONFIG_PATH=$BUILD/lib/pkgconfig ./configure --toolchain=msvc --extra-cflags='-MDd -I$BUILD/include' --extra-ldflags='-LIBPATH:$BUILD/lib' --prefix=$BUILD --pkg-config-flags='--static' --disable-doc --disable-shared --enable-static --enable-runtime-cpudetect --disable-devices --disable-demuxers --disable-decoders --disable-network --enable-w32threads --enable-gpl
          ls -laR $BUILD
