name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'

jobs:

  FFmpeg:
    runs-on: windows-2019
    needs: []
    steps:
      - name: Set up development tools
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          FOR /F "delims==" %%G IN ('where cl.exe') DO SET _cl_path=%%G > vars.sh
          echo CL_EXEC="%_cl_path%" >> vars.sh
          echo WSL_CL_EXEC=$(wslpath -u "$CL_EXEC") >> vars.sh
          echo WSL_CL_PATH=$(dirname "$WSL_CL_EXEC") >> vars.sh
          echo export PATH=$PATH:$WSL_CL_PATH >> vars.sh
          echo export DevEnvDir="%DevEnvDir% " >> vars.sh
          echo export INCLUDE="%INCLUDE% " >> vars.sh
          echo export LIB="%LIB% " >> vars.sh
          echo export LIBPATH="%LIBPATH% " >> vars.sh
          echo export VCINSTALLDIR="%VCINSTALLDIR% " >> vars.sh
          echo export VSINSTALLDIR="%VSINSTALLDIR% " >> vars.sh
          echo export VisualStudioVersion="%VisualStudioVersion% " >> vars.sh
          echo export WSLcross=true >> vars.sh
          echo export WSLENV=$WSLENV:INCLUDE/w:LIB/w:LIBPATH/w >> vars.sh
      - name: Set up WSL
        uses: Vampire/setup-wsl@v1.2.0
        with:
          additional-packages:
            dos2unix
      - name: Build FFmpeg
        shell: wsl-bash {0}
        run: |
          ./vars.sh
          echo $ABC
          echo $PATH
          cl.exe
          MSBuild.exe
          

          
