name: Build all FFmpeg versions

on:
  workflow_dispatch:

jobs:
  ffmpeg-static-debug:
    uses: ./.github/workflows/ffmpeg.yml
    with:
      source: cartwheel
      type: static
      config: debug
      ffmpegRef: master
      nvencRef: sdk/9.1
      amfRef: master

  ffmpeg-static-release:
    uses: ./.github/workflows/ffmpeg.yml
    with:
      source: cartwheel
      type: static
      config: release
      ffmpegRef: master
      nvencRef: sdk/9.1
      amfRef: master
      
  ffmpeg-shared-debug:
    uses: ./.github/workflows/ffmpeg.yml
    with:
      source: ffmpeg
      type: shared
      config: debug
      ffmpegRef: release/5.0
      nvencRef: sdk/11.0
      amfRef: master
      
