name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'

jobs:

  FFmpeg:
    runs-on: windows-2019
    needs: []
    steps:
      - name: Set up WSL
        uses: Vampire/setup-wsl@v1.2.0
        with:
          distribution: Debian
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Set up cache
        uses: actions/cache@v2
        env:
          cache-name: cache-ffmpeg
        with:
          path: ~/build
          key: ${{ env.cache-name }}
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          repository: FFmpeg/FFmpeg.git
          ref: release/5.0
          path: repo
#      - name: Get artifacts
#        uses: actions/download-artifact@master
#        with:
#          name: oneVPL
      - name: Build FFmpeg
        shell: wsl-bash {0}
        run: |
          PATH=/mnt/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64:/mnt/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin:$PATH
          mkdir build
          #BUILD=$(realpath build)
          #tar zxf *.tgz -C build
          cd repo
          PKG_CONFIG_PATH=../build/lib/pkgconfig ./configure --toolchain=msvc --extra-cflags='-MDd -I../build/include' --extra-ldflags='-LIBPATH:../build/lib' --prefix=../build --pkg-config-flags='--static' --disable-doc --disable-shared --enable-static --enable-runtime-cpudetect --disable-devices --disable-demuxers --disable-decoders --disable-network --enable-w32threads --enable-gpl
          ls -laR ../build
          
