name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'
        
jobs:

  ffmpeg:
    runs-on: windows-2019
    needs: []
    steps:
      - name: Set up GIT
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout FFmpeg
        uses: actions/checkout@v3.0.0
        with:
          repository: FFmpeg/FFmpeg.git
          ref: release/5.0
          path: repo
      - name: Set up WSL
        uses: Vampire/setup-wsl@v1.2.0
        with:
          additional-packages:
            pkg-config
      - uses: suisei-cn/actions-download-file@v1
        name: Set up NASM
        with:
          url: "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip"
          target: .
      - name: Configure
        shell: cmd
        run: |
          bash.exe -c "unzip -j nasm-2.15.05-win64.zip -d /usr/bin > /dev/null"
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          md build
          bash.exe -c "export BUILD=$(realpath build) ; cd repo ; PKG_CONFIG_PATH=$BUILD/lib/pkgconfig ./configure --toolchain=msvc --extra-cflags='-MDd -I$BUILD/include' --extra-ldflags='-LIBPATH:$BUILD/lib' --prefix=$BUILD --pkg-config-flags='--static' --disable-doc --disable-shared --enable-static --enable-runtime-cpudetect --disable-devices --disable-demuxers --disable-decoders --disable-network --enable-w32threads --enable-gpl ; make ; make install"
          dir ../build
