name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'

jobs:

  FFmpeg:
    runs-on: windows-2019
    needs: []
    steps:
      - name: Set up WSL
        uses: Vampire/setup-wsl@v1.2.0
        with:
          distribution: Debian
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Set up cache
        uses: actions/cache@v2
        env:
          cache-name: cache-ffmpeg
        with:
          path: ~/build
          key: ${{ env.cache-name }}
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          repository: https://github.com/FFmpeg/FFmpeg.git
          ref: release/5.0
          path: repo
#      - name: Get artifacts
#        uses: actions/download-artifact@master
#        with:
#          name: oneVPL
      - name: Build FFmpeg
        shell: wsl-bash {0}
        run: |
          mkdir build
          BUILD=$(realpath build)
          tar zxf *.tgz -C build
          cd repo
          PKG_CONFIG_PATH=../repo/lib/pkgconfig ./configure --toolchain=msvc --extra-cflags='-MDd -I../repo/include' --extra-ldflags='-LIBPATH:../repo/lib' --prefix=../repo --pkg-config-flags='--static' --disable-doc --disable-shared --enable-static --enable-runtime-cpudetect --disable-devices --disable-demuxers --disable-decoders --disable-network --enable-w32threads --enable-gpl
          ls -laR $BUILD
