name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'
        
jobs:

  FFmpeg:
    runs-on: windows-2019
    needs: []
    steps:
      - name: Set up WSL
        uses: Vampire/setup-wsl@v1.2.0
      - name: Set up development tools
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          bash.exe -c set
