name: Build all FFmpeg versions

on:
  workflow_dispatch:
  schedule:
  - cron: "0 1 * * *"

jobs:
  ffmpeg-static-debug:
    uses: ./.github/workflows/ffmpeg.yml
    with:
      env: windows-2022
      source: cartwheel
      type: static
      config: debug
      ffmpegRef: master
      nvencRef: sdk/9.1
      amfRef: master

  ffmpeg-static-release:
    uses: ./.github/workflows/ffmpeg.yml
    with:
      env: windows-2022
      source: cartwheel
      type: static
      config: release
      ffmpegRef: master
      nvencRef: sdk/9.1
      amfRef: master
      
