name: FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'
        
env:
  vsPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
  msysConfig: debug
  winConfig: Debug
  cFlags: -MDd

jobs:
  libogg:
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: base-devel binutils autotools automake
        path-type: inherit
    - name: Set up cache
      uses: actions/cache@v2
      env:
        cache-name: cache-ffmpeg-${{ env.msysConfig }}
      with:
        path: cache
        key: cache-key
    - name: Set up GIT
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: Checkout LibOGG
      uses: actions/checkout@v3.0.0
      with:
        repository: xiph/ogg
        ref: master
        path: repo
    - name: Build LibOGG
      shell: cmd
      run: |
        call "${{ env.vsPath }}VC\Auxiliary\Build\vcvars64.bat"
        md build dist
        D:\a\_temp\setup-msys2\msys2.cmd -c 'cd repo ; autoreconf -i ; CC=cl.exe CXX=cl.exe CXXFLAGS=${{ env.cFlags }} ./configure --prefix=$(realpath ../build) --disable-shared ; make -j ; make install ; cd ../build ; tar czf ../dist/libogg.tgz'
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: libogg
        path: dist/libogg.tgz
  
  nvenc:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"

  amf:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"
        
  onevpl:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"
        
  libsvtav1:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"
    
  libvorbis:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"
    
  libsnappy:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"

  libvpx:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"

  libfdk-aac:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"

  libmp3lame:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"

  libzimg:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"

  libopus:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"

  libx264:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"

  libx265:
    if: ${{ false }}
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      run: echo "bla"

  ffmpeg:
    if: ${{ false }}
    runs-on: windows-2019
    needs: [nvenc,amf,onevpl,libsvtav1,libvorbis,libsnappy,libvpx,libfdk-aac,libmp3lame,libzimg,libopus,libogg,libx264,libx265]
    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: base-devel binutils mingw-w64-x86_64-cmake nasm
          path-type: inherit
      - name: Set up GIT
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout FFmpeg
        uses: actions/checkout@v3.0.0
        with:
          repository: FFmpeg/FFmpeg.git
          ref: release/5.0
          path: repo
      - name: Build FFmpeg
        shell: cmd
        run: |
          call "${{ env.vsPath }}VC\Auxiliary\Build\vcvars64.bat"
          md build dist
          D:\a\_temp\setup-msys2\msys2.cmd -c 'cd repo ; PKG_CONFIG_PATH=../build/lib/pkgconfig ./configure --toolchain=msvc --extra-cflags="${{ env.cFlags }} -I../build/include" --extra-ldflags="-LIBPATH:../build/lib" --prefix=../build --pkg-config-flags="--static" --disable-doc --disable-shared --enable-static --enable-runtime-cpudetect --disable-devices --disable-demuxers --disable-decoders --disable-network --enable-w32threads --enable-gpl ; make ; make install ; cd ../build/lib ; for file in *.a; do mv "$file" "`basename "$file" .a`.lib"; done ; rm -rf fdk-aac.lib pkgconfig *.la ../share ; cd .. ; tar czf ../dist/ffmpeg-win64-static-${{ env.msysConfig }}.tar.gz *'
      - name: Publish FFmpeg artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Nightly Build (${{ env.winConfig }})
          path: dist/ffmpeg-win64-static-${{ env.msysConfig }}.tar.gz
