name: FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'

jobs:

  FFmpeg:
    runs-on: windows-2022
    needs: []
    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: base-devel binutils mingw-w64-x86_64-cmake nasm
          path-type: inherit
      - name: Clone FFmpeg 5.0
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git clone -b release/5.0 https://github.com/FFmpeg/FFmpeg.git repo
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          md build dist
          D:\a\_temp\setup-msys2\msys2.cmd -c 'cd repo ; PKG_CONFIG_PATH=../build/lib/pkgconfig ./configure --toolchain=msvc --extra-cflags="-MDd -I../build/include" --extra-ldflags="-LIBPATH:../build/lib" --prefix=../build --pkg-config-flags="--static" --disable-doc --disable-shared --enable-static --enable-runtime-cpudetect --disable-devices --disable-demuxers --disable-muxer=asf --disable-decoders --disable-network --enable-w32threads --enable-gpl ; make -j ; make install ; cd ../build/lib ; for file in *.a; do mv "$file" "`basename "$file" .a`.lib"; done ; rm -rf fdk-aac.lib *.la ; tar czf ../../dist/ffmpeg-win64-static-debug.tar.gz * ; ls -la ..'
