name: FFmpeg

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'

jobs:

  FFmpeg:
    runs-on: windows-2019
    needs: []
    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: base-devel binutils mingw-w64-x86_64-cmake pkg-config git
          path-type: inherit
      - name: Clone FFmpeg 5.0
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git clone -b release/5.0 https://github.com/FFmpeg/FFmpeg.git repo
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          md build
          D:\a\_temp\setup-msys2\msys2.cmd -c 'export BUILD=../build ; cd repo ; PKG_CONFIG_PATH=$BUILD/lib/pkgconfig ./configure --toolchain=msvc --extra-cflags="-MDd -I$BUILD/include" --extra-ldflags="-LIBPATH:$BUILD/lib" --prefix=$BUILD --pkg-config-flags="--static" --disable-doc --disable-shared --enable-static --enable-runtime-cpudetect --disable-devices --disable-demuxers --disable-decoders --disable-network --enable-w32threads --enable-gpl ; make -j ; make install'
