name: LibFDKAAC

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'
        
jobs:

  libfdk-aac:
    runs-on: windows-2019
    steps:
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: base-devel binutils autotools automake mingw-w64-x86_64-cmake nasm
        path-type: inherit
    - name: Set up cache
      uses: actions/cache@v2
      env:
        cache-name: cache-ffmpeg-${{ env.msysConfig }}
      with:
        path: cache
        key: cache-key
    - name: Set up GIT
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: Checkout FDK AAC
      uses: actions/checkout@v3.0.0
      with:
        repository: mstorsjo/fdk-aac
        ref: master
        path: fdk-aac
    - name: Build FDK AAC
      shell: cmd
      run: |
        call "${{ env.vsPath }}VC\Auxiliary\Build\vcvars64.bat"
        md build dist
        D:\a\_temp\setup-msys2\msys2.cmd -c 'cd fdk-aac ; autoreconf -i ; CC=cl.exe CXX=cl.exe CXXFLAGS=${{ env.cFlags }} ./configure --prefix=$(realpath ../build) --disable-shared --disable-static ; make -j ; make install ; cd ../build ; tar czf ../dist/libfdkaac.tgz *'
        #patch -N -p1 -i ../../patches/0003-dynamic-loading-of-shared-fdk-aac-library-5.0.patch  
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: libfdkaac
        path: dist/libfdkaac.tgz
