name: test

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration'     
        required: true
        default: 'Debug'
     
env:
  vsPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
  msysConfig: debug
  winConfig: Debug
  cFlags: -MDd
  switches: "--enable-encoder=libvpl --enable-encoder=libsvtav1 --enable-encoder=libsnappy --enable-encoder=libvpx --enable-encoder=libmp3lame --enable-encoder=libzimg --enable-encoder=libopus --enable-encoder=libogg --enable-encoder=libvorbis --enable-encoder=libx264"
 
jobs:

  libx265:
    runs-on: windows-2019
    steps:
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Set up NASM
      uses: ilammy/setup-nasm@v1.2.1
    - name: Set up dependant libs
      uses: actions/download-artifact@v3
      with:
        path: build
    - name: Build X265
      shell: cmd
      run: |
        call "${{ env.vsPath }}VC\Auxiliary\Build\vcvars64.bat"
        md build dist
        cd x265/build/vc15-x86_64
        md work
        cd work
        dir "${{ env.vsPath }}VC\Tools"
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: x265
        path: dist/x265.lib
