name: 'Test'

on:
  workflow_dispatch:
    inputs:
      system:
        type: choice
        required: true
        default: 'windows-2022' 
        description: 'System'
        options: 
        - windows-2022

      type:
        type: choice
        required: true
        default: 'shared' 
        description: Type
        options: 
        - static
        - shared

      config:
        type: choice
        required: true
        default: 'release' 
        description: 'Configuration'
        options: 
        - debug
        - release
        
      ffmpegRef:
        type: string
        required: true
        default: 'release/6.1' 
        description: 'FFmpeg refId'
        
  workflow_call:
    inputs:
      system:
        type: string
        required: true
      type:
        type: string
        required: true
      config:
        type: string
        required: true
      ffmpegRef:
        type: string
        required: true
        
env:
  vsPath: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\
  COMPONENTS: "--enable-libvpl --enable-libsvtav1 --enable-libsnappy --enable-libmp3lame --enable-libzimg --enable-libvpx --enable-libopus --enable-libkvazaar"
  #--enable-libvorbis
  NASM_EXECUTABLE: nasm
  cFlags: ${{ inputs.config == 'release' && '-MD' || '-MDd' }}
  variant: ${{ inputs.type == 'static' && ' --pkg-config-flags="--static" --disable-shared --enable-static' || ' --disable-static --enable-shared --build-suffix=-voukoderpro' }}
  msbuildConfig: ${{ inputs.config == 'release' && 'Release' || 'Debug' }}

jobs:
  libkvazaar:
    runs-on: ${{ inputs.system }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/libkvazaar
      with:
        refId: v2.3.0
        config: ${{ inputs.config }}

